[workspace]
members = [
  "blockchain",
  "cli",
  "consense",
  "crypto",
  "node",
  "p2p",
  "txpool",
  "types",
  "wallet",
]

[profile.dev]
overflow-checks = true
panic = "unwind"

[profile.release]
incremental = false
lto = true
overflow-checks = false
panic = "unwind"
